### ISSUE TITLE
Give placeholder content for resolving ISO 19112 links

### ISSUE THREAD

**Issue by ronaldtse** [ISO-TC211/standards.isotc211.org#1]
> ISO 19112 has the following links:
> http://standards.isotc211.org/19112/-1/2/conf/srs
> http://standards.isotc211.org/19112/-1/2/req/srs
> http://standards.isotc211.org/19112/-1/2/conf/gaz
> http://standards.isotc211.org/19112/-1/2/req/gaz
> http://standards.isotc211.org/19112/-1/2/req/srs/srs
> http://standards.isotc211.org/19112/-1/2/req/gaz/sch
> http://standards.isotc211.org/19112/-1/2/req/gaz/mng
> http://standards.isotc211.org/19112/-1/2/conf/srs/srs
> http://standards.isotc211.org/19112/-1/2/conf/gaz/sch
> http://standards.isotc211.org/19112/-1/2/conf/gaz/mng

From https://github.com/ISO-TC211/www.isotc211.org/issues/8

**Comment by jetgeo** [comment]
@ronaldtse : There is no content yet, but we should have empty folders anyhow, to assure resolvable links.

**Comment by ronaldtse** [comment]
@jetgeo the links are resolvable now (give it few minutes to redeploy)
